scoPath <- system.file('testdata', 'scObj.qs', package='GSABenchmark')
scObj <- qs::qread(scoPath)
gsPath <- system.file('testdata', 'geneSets.qs', package='GSABenchmark')
geneSets <- qs::qread(gsPath)
sPath <- system.file('testdata', 'smr.qs', package='GSABenchmark')
smr <- qs::qread(sPath)
