scoPath <- system.file('extdata', 'scObj.qs2', package='GSABenchmark')
scObj <- qs2::qs_read(scoPath)
gsPath <- system.file('extdata', 'geneSets.qs2', package='GSABenchmark')
geneSets <- qs2::qs_read(gsPath)
sPath <- system.file('extdata', 'smr.qs2', package='GSABenchmark')
smr <- qs2::qs_read(sPath)
